' ******************************************************************************
' UML PlantUML diagram that shows the Remal Docker container hierarchy.
'
' Since : July 2023
' Author: Arnold Somogyi <arnold.somogyi@gmail.com>
'
' Copyright (c) 2020-2025 Remal Software and Arnold Somogyi All rights reserved
' ******************************************************************************
@startuml

<style>
  .STYLE_EXTERNAL {
    RoundCorner 20
    LineThickness 2
    LineColor #FF6F00
    BackgroundColor #FFD740
  }
  .STYLE_BASE {
    RoundCorner 20
    LineThickness 2
    LineColor #33691E
    BackgroundColor #CCFF90
  }
  .STYLE_CORE {
    RoundCorner 20
    LineThickness 2
    LineColor #33691E
    BackgroundColor #76FF03
  }
  .STYLE_INFRA {
    RoundCorner 20
    LineThickness 2
    LineColor #006064
    BackgroundColor #84FFFF
  }
  .STYLE_APP {
    RoundCorner 20
    LineThickness 2
    LineColor #006064
    BackgroundColor #00E5FF
  }
  .STYLE_MONITOR {
    RoundCorner 20
    LineThickness 2
    LineColor #880E4F
    BackgroundColor #FF80AB
  }
</style>

skinparam ArrowThickness 2
skinparam ArrowColor #607D8B

skinparam titleFontSize 26
skinparam titleFontColor #607D8B
skinparam titleBackgroundColor #FFFFFF
skinparam titleFontStyle bold

title **Remal Docker image hierarchy**

sprite $EXTERNAL_IMAGE jar:archimate/meaning
sprite $BASE_IMAGE     jar:archimate/goal
sprite $CORE_IMAGE     jar:archimate/interaction
sprite $INFRA_IMAGE    jar:archimate/network
sprite $APP_IMAGE      jar:archimate/physical-equipment
sprite $MONITOR_IMAGE  jar:archimate/assignment

rectangle "alpine"                       as alpine          <<$EXTERNAL_IMAGE>> <<STYLE_EXTERNAL>>
rectangle "zookeeper"                    as zookeeper       <<$EXTERNAL_IMAGE>> <<STYLE_EXTERNAL>>
rectangle "kafka"                        as kafka           <<$EXTERNAL_IMAGE>> <<STYLE_EXTERNAL>>
rectangle "remal-base"                   as base            <<$BASE_IMAGE>>     <<STYLE_BASE>>
rectangle "OpenJDK-11"                   as java11          <<$CORE_IMAGE>>     <<STYLE_CORE>>
rectangle "OpenJDK-17"                   as java17          <<$CORE_IMAGE>>     <<STYLE_CORE>>
rectangle "OpenJDK-21"                   as java21          <<$CORE_IMAGE>>     <<STYLE_CORE>>
rectangle "Private PKI"                  as pki             <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Apache Tomcat 9"              as tomcat9         <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "ForgeRock Directory Services" as ds              <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "ForgeRock Access Management"  as am              <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Hashicorp Vault"              as vault           <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Hashicorp Consul"             as consul          <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Hashicorp Consul"             as consul          <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Java-21 Runner"               as java_runner_21  <<$APP_IMAGE>>      <<STYLE_APP>>
rectangle "Java-21 Runner + PostgreSQL"  as java_runner_21p <<$APP_IMAGE>>      <<STYLE_APP>>
rectangle "Java-21 Omni Runner"          as java_runner_21o <<$APP_IMAGE>>      <<STYLE_APP>>
rectangle "Hazelcast"                    as hazelcast       <<$INFRA_IMAGE>>    <<STYLE_INFRA>>
rectangle "Prometheus"                   as prometheus      <<$MONITOR_IMAGE>>  <<STYLE_MONITOR>>
rectangle "Grafana"                      as grafana         <<$MONITOR_IMAGE>>  <<STYLE_MONITOR>>

alpine --> base
base --> java11
base --> java17
base --> java21
java17 --> pki
base ---> vault
base ------> prometheus
base ------> grafana
java11 --> tomcat9
java17 --> ds
java21 --> consul
java21 --> hazelcast
tomcat9 --> am
consul --> java_runner_21
java_runner_21 --> java_runner_21p
java_runner_21p --> java_runner_21o

@enduml
