### get user
GET https://localhost:14114/api/user/zappee

### save user
POST https://localhost:14114/api/user/
Content-Type: application/json

{
  "username": "zappee",
  "firstName": "Arnold",
  "email": "arnold@gmail.com",
  "description": "Java developer"
}

### send one message to Kafka topic
GET https://localhost:14314/api/kafka/send-one

### send multiple message to Kafka topic
GET https://localhost:14314/api/kafka/send-multiple

### send a custom message to Kafka topic
POST https://localhost:14314/api/kafka/send
Content-Type: application/json

{
  "sourceSystem": "whatewer system",
  "owner": "peter",
  "payload": "{\"comment\": \"a custom event from the rest endpoint\"}",
  "createdInUtc": [
    2025,
    1,
    20,
    21,
    33,
    13
  ]
}

### simulate a failure while processing the incoming Kafka message
POST https://localhost:14314/api/kafka/send
Content-Type: application/json

{
  "sourceSystem": "wrong system",
  "owner": "error",
  "payload": "{\"comment\": \"an error event from the rest endpoint\"}"
}
