version: '3'
services:
    # ----- Private Certificate Authority Server -------------------------------
    pki:
        image: remal-private-ca:0.0.1
        container_name: pki.${DOMAIN_NAME}
        hostname: pki.${DOMAIN_NAME}
        ports:
            - "13012:22"   # SSH
        environment:
            - EASYRSA_REQ_CN=${DOMAIN_NAME}
            - EASYRSA_REQ_COUNTRY=${EASYRSA_REQ_COUNTRY}
            - EASYRSA_REQ_PROVINCE=${EASYRSA_REQ_PROVINCE}
            - EASYRSA_REQ_CITY=${EASYRSA_REQ_CITY}
            - EASYRSA_REQ_ORG=${EASYRSA_REQ_ORG}

    # ----- LDAP Directory Server ----------------------------------------------
    ds:
        image: remal-ds-7.3:0.0.1
        container_name: ds.${DOMAIN_NAME}
        hostname: ds.${DOMAIN_NAME}
        depends_on:
            - pki
        ports:
            - "13032:22"   # SSH
            - "13034:4444" # admin connector port
            - "13036:636"  # LDAP over SSL
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}
            - NEW_DS_DEPLOYMENT_KEY=false
            - DS_CONFIG_BACKUP=false
            - DS_CONFIG_RESTORE_FROM=xlatest
            - AM_IDENTITY_STORE_BACKUP=false
            - AM_IDENTITY_STORE_RESTORE_FROM=xlatest
            - AM_CONFIG_STORE_BACKUP=false
            - AM_CONFIG_STORE_RESTORE_FROM=xlatest
        volumes:
            - $HOME/dev/workspace/java/remal/gombi/backups/containers:/opt/opendj/backup

    # ----- Access Management Server -------------------------------------------
    forgerock-am:
        image: remal-am-7.3:0.0.1
        container_name: am.${DOMAIN_NAME}
        hostname: am.${DOMAIN_NAME}
        depends_on:
            - pki
        ports:
            - "13042:22"   # SSH
            - "13048:8080" # HTTP
            - "13044:443"  # HTTPS
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}
            - AM_CONFIG_STORE_HOST=ds.${DOMAIN_NAME}
            - AM_USER_STORE_HOST=ds.${DOMAIN_NAME}
            - AM_CONFIG_BACKUP=false
            - AM_CONFIG_RESTORE_FROM=xlatest
        volumes:
            - $HOME/dev/workspace/java/remal/gombi/backups/containers:/opt/openam/backup

    # ----- Hashicorp Vault ----------------------------------------------------
    vault:
        image: remal-vault-1.14:0.0.1
        container_name: vault.${DOMAIN_NAME}
        hostname: vault.${DOMAIN_NAME}
        depends_on:
            - pki
        ports:
            - "13052:22"   # SSH
            - "13058:8200" # vault listening
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}

    # ----- Hashicorp Consul ---------------------------------------------------
    consul:
        image: remal-consul-1.17:0.0.1
        container_name: consul.hello.com
        hostname: consul.hello.com
        depends_on:
            - pki
        ports:
            - "13062:22"   # SSH
            - "13063:8501" # Consul UI HTTPS
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}

    # ----- Services -----------------------------------------------------------
    hello-service-1:
        image: remal-java-17-runner:0.0.1
        container_name: hello-service-1.hello.com
        hostname: hello-service-1.hello.com
        depends_on:
            - consul
        ports:
            - "14212:22"   # SSH
            - "14213:8000" # JVM debug
            - "14214:8443" # HTTPS
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}
            - CONSUL_SERVER_HOSTNAME=consul.${DOMAIN_NAME}
        volumes:
            - $HOME/dev/workspace/java/remal/gombi-jars/hello:/jar-to-run

    user-service-1:
        image: remal-java-17-runner:0.0.1
        container_name: user-service-1.hello.com
        hostname: user-service-1.hello.com
        depends_on:
            - consul
        ports:
            - "14112:22"   # SSH
            - "14113:8000" # JVM debug
            - "14114:8443" # HTTPS
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}
            - CONSUL_SERVER_HOSTNAME=consul.${DOMAIN_NAME}
        volumes:
            - $HOME/dev/workspace/java/remal/gombi-jars/user:/jar-to-run

    user-service-2:
        image: remal-java-17-runner:0.0.1
        container_name: user-service-2.hello.com
        hostname: user-service-2.hello.com
        depends_on:
            - consul
        ports:
            - "14122:22"   # SSH
            - "14123:8000" # JVM debug
            - "14124:8443" # HTTPS
        environment:
            - PKI_HOST=pki.${DOMAIN_NAME}
            - CONSUL_SERVER_HOSTNAME=consul.${DOMAIN_NAME}
        volumes:
            - $HOME/dev/workspace/java/remal/gombi-jars/user:/jar-to-run
