version: '3'
services:
    # ----- Private Certificate Authority Server -------------------------------
    pki:
        image: private-ca:0.0.1-remal
        container_name: pki.hello.com
        hostname: pki.hello.com
        ports:
            - "13012:22"   # SSH
        environment:
            - EASYRSA_REQ_CN=hello.com
            - EASYRSA_REQ_COUNTRY=DK
            - EASYRSA_REQ_PROVINCE=Region Hovedstaden
            - EASYRSA_REQ_CITY=Copenhagen
            - EASYRSA_REQ_ORG=Hello Software

    # ----- LDAP directory service ---------------------------------------------
    ds:
        image: ds-7.3:0.0.1-remal
        container_name: ds.hello.com
        hostname: ds.hello.com
        ports:
            - "13022:22"   # SSH
            - "13024:4444" # admin connector port
            - "13026:636"  # LDAP over SSL
        environment:
            - PKI_HOST=pki.hello.com
            - NEW_DS_DEPLOYMENT_KEY=false
            - DS_CONFIG_BACKUP=false
            - DS_CONFIG_RESTORE_FROM=xlatest
            - AM_IDENTITY_STORE_BACKUP=false
            - AM_IDENTITY_STORE_RESTORE_FROM=xlatest
            - AM_CONFIG_STORE_BACKUP=false
            - AM_CONFIG_STORE_RESTORE_FROM=xlatest
        volumes:
            - $HOME/dev/workspace/java/remal/gombi/backups/containers:/opt/opendj/backup

    # ----- Access Management service ------------------------------------------
    forgerock-am:
        image: am-7.3:0.0.1-remal
        container_name: am.hello.com
        hostname: am.hello.com
        ports:
            - "13032:22"   # SSH
            - "13038:8080" # HTTP
            - "13034:443"  # HTTPS
            - "13036:50636"  # LDAP over SSL
        environment:
            - PKI_HOST=pki.hello.com
            - AM_CONFIG_STORE_HOST=ds.hello.com
            - AM_USER_STORE_HOST=ds.hello.com
            - AM_CONFIG_BACKUP=false
            - AM_CONFIG_RESTORE_FROM=xlatest
        volumes:
            - $HOME/dev/workspace/java/remal/gombi/backups/containers:/opt/openam/backup

    # ----- Vault service ------------------------------------------------------
    vault:
        image: vault-1.14:0.0.1-remal
        container_name: vault.hello.com
        hostname: vault.hello.com
        ports:
            - "13042:22"   # SSH
            - "13048:8200" # vault listening
        environment:
            - PKI_HOST=pki.hello.com
