#!/bin/bash -ue
# ******************************************************************************
#  ForgeRock Directory Server installation script.
#
#  Since : May, 2023
#  Author: Arnold Somogyi <arnold.somogyi@gmail.com>
#
#  Copyright (c) 2020-2023 Remal Software and Arnold Somogyi All rights reserved
# ******************************************************************************
source /shared.sh
source /ds-functions.sh

# ------------------------------------------------------------------------------
# Generates and saves a new ForgeRock Directory Server deployment-key.
# A deployment key is a random string generated by DS software. A deployment key
# password is a secret string at least 8 characters long that you choose. The
# two are a pair. You must have a deployment key's password to use the key.
# ------------------------------------------------------------------------------
function generate_ds_deployment_key() {
  printf "%s | [INFO]  generating a new ForgeRock Directory Server deployment-key...\n" "$(date +"%Y-%b-%d %H:%M:%S")"

  cd "$DS_HOME"
  local deployment_key deployment_key_password
  deployment_key_password="password"
  deployment_key="$(bin/dskeymgr create-deployment-id --deploymentIdPassword "$deployment_key_password")"

  mkdir -p "$(dirname "$DEPLOYMENT_KEY_FILE")"
  printf "KEY=%s\n" "$deployment_key" > "$DEPLOYMENT_KEY_FILE"
  printf "PASSWORD=%s\n" "$deployment_key_password" >> "$DEPLOYMENT_KEY_FILE"

  printf "%s | [DEBUG]    deployment key file: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$DEPLOYMENT_KEY_FILE"
  printf "%s | [DEBUG]         deployment key: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key"
  printf "%s | [DEBUG]   password for the key: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key_password"
  printf "%s | [INFO ] deployment-key has been saved\n" "$(date +"%Y-%b-%d %H:%M:%S")"
}

# ------------------------------------------------------------------------------
# Generates a new maser key.
# The master key is a certificate generated by the dskeymgr tool based on the
# deployment key and deployment password. The master key sits in a PKCS#12
# keystore.
#
# Arguments
#    arg 1:  keystore file
#    arg 2:  keystore password
# ------------------------------------------------------------------------------
function generate_ds_master_key() {
  local alias keystore_file keystore_password
  alias="master-key"
  keystore_file="$1"
  keystore_password="$2"

  local deployment_key deployment_key_password
  deployment_key=$(get_value "$DEPLOYMENT_KEY_FILE" "KEY")
  deployment_key_password=$(get_value "$DEPLOYMENT_KEY_FILE" "PASSWORD")

  printf "%s | [INFO]  creating a new ForgeRock Directory Server master-key...\n" "$(date +"%Y-%b-%d %H:%M:%S")"
  printf "%s | [DEBUG]                DS_HOME: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$DS_HOME"
  printf "%s | [DEBUG]                  alias: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$alias"
  printf "%s | [DEBUG]    deployment key file: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$DEPLOYMENT_KEY_FILE"
  printf "%s | [DEBUG]         deployment key: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key"
  printf "%s | [DEBUG]   password for the key: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key_password"
  printf "%s | [DEBUG]               keystore: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$keystore_file"
  printf "%s | [DEBUG]      keystore password: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$keystore_password"

  "$DS_HOME/bin/dskeymgr" export-master-key-pair \
    --alias "$alias" \
    --deploymentKey "$deployment_key" \
    --deploymentKeyPassword "$deployment_key_password" \
    --keyStoreFile "$keystore_file" \
    --keyStorePassword "$keystore_password"
}

# ------------------------------------------------------------------------------
# ForgeRock Directory Server installation.
# ------------------------------------------------------------------------------
function install_ds() {
  local deployment_key deployment_key_password
  deployment_key=$(get_value "$DEPLOYMENT_KEY_FILE" "KEY")
  deployment_key_password=$(get_value "$DEPLOYMENT_KEY_FILE" "PASSWORD")

  local truststore_file truststore_password
  truststore_file=$(readlink -f "$JAVA_HOME/lib/security/cacerts")
  truststore_password="changeit"

  local fqdn domain
  fqdn=$(hostname -f)
  domain=$(hostname -d)

  local keystore_file keystore_password
  keystore_file="/tmp/$fqdn.p12"
  keystore_password="changeit"

  local server_id domain_dn profile_config profile_store base_dn_config base_dn_store
  server_id="master-ldap"
  domain_dn=$(fqdn_to_ldap_dn "$domain")
  ds_profile_config="am-config"
  ds_profile_store="am-identity-store"
  base_dn_config="ou=am-config,$domain_dn"
  base_dn_store="ou=am-identity,$domain_dn"

  printf "%s | [INFO]  installing ForgeRock Directory Service (DS)...\n" "$(date +"%Y-%b-%d %H:%M:%S")"
  printf "%s | [DEBUG]                       FQDN: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$fqdn"
  printf "%s | [DEBUG]                     domain: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$domain"
  printf "%s | [DEBUG]                  domain DN: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$domain_dn"
  printf "%s | [DEBUG]                    DS_HOME: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$DS_HOME"
  printf "%s | [DEBUG]                  server-id: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$server_id"
  printf "%s | [DEBUG]                DS profiles: \"%s\", \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$ds_profile_config" "$ds_profile_store"
  printf "%s | [DEBUG]                    base DN: \"%s\", \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$base_dn_config" "$base_dn_store"
  printf "%s | [DEBUG]             deployment-key: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key"
  printf "%s | [DEBUG]    deployment-key password: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$deployment_key_password"
  printf "%s | [DEBUG]               ldap user DN: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$LDAP_USER_DN"
  printf "%s | [DEBUG]         ldap user password: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$LDAP_USER_PASSWORD"
  printf "%s | [DEBUG]       admin connector port: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$ADMIN_CONNECTOR_PORT"
  printf "%s | [DEBUG]                  LDAP port: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$LDAP_PORT"
  printf "%s | [DEBUG]                 LDAPS port: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$LDAPS_PORT"
  printf "%s | [DEBUG]            truststore file: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$truststore_file"
  printf "%s | [DEBUG]        truststore password: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$truststore_password"
  printf "%s | [DEBUG]              keystore file: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$keystore_file"
  printf "%s | [DEBUG]          keystore password: \"%s\"\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$keystore_password"
  printf "%s | [INFO ] setting up directory-server\n" "$(date +"%Y-%b-%d %H:%M:%S")"

  cd "$DS_HOME"
  ./setup \
    --serverId "$server_id" \
    --profile "$ds_profile_config" \
    --profile "$ds_profile_store" \
    --deploymentId "$deployment_key" \
    --deploymentIdPassword "$deployment_key_password" \
    --rootUserDN "$LDAP_USER_DN" \
    --rootUserPassword "$LDAP_USER_PASSWORD" \
    --hostname "$fqdn" \
    --adminConnectorPort "$ADMIN_CONNECTOR_PORT" \
    --ldapPort "$LDAP_PORT" \
    --enableStartTls \
    --ldapsPort "$LDAPS_PORT" \
    --acceptLicense \
    --set am-config/backendName:"$ds_profile_config" \
    --set am-config/baseDn:"$base_dn_config" \
    --set am-config/amConfigAdminPassword:"$LDAP_USER_PASSWORD" \
    --set am-identity-store/backendName:"$ds_profile_store" \
    --set am-identity-store/baseDn:"$base_dn_store" \
    --set am-identity-store/amIdentityStoreAdminPassword:"$LDAP_USER_PASSWORD" \
    --usePkcs12KeyStore "$keystore_file" \
    --keyStorePassword "$keystore_password" \
    --certNickname "$fqdn" \
    --usePkcs12TrustStore "$keystore_file" \
    --trustStorePassword "$keystore_password"
}

# ------------------------------------------------------------------------------
#  Main program starts here.
# ------------------------------------------------------------------------------
printf "%s | [DEBUG] -----------------------------------------------------------\n" "$(date +"%Y-%b-%d %H:%M:%S")"
printf "%s | [DEBUG] executing the \"%s\" script...\n" "$(date +"%Y-%b-%d %H:%M:%S")" "$0"
printf "%s | [DEBUG] ===========================================================\n" "$(date +"%Y-%b-%d %H:%M:%S")"

FQDN=$(hostname -f)
KEYSTORE_HOME="/tmp"
KEYSTORE_FILE="$FQDN.p12"
KEYSTORE_PASSWORD="changeit"

generate_certificate "$FQDN"
copy_from_remote_machine "$PKI_HOST" "$SSH_USER" "$SSH_PASSWORD" "/opt/easy-rsa/pki/private/$KEYSTORE_FILE" "$KEYSTORE_HOME"
generate_ds_deployment_key
generate_ds_master_key "$KEYSTORE_HOME/$KEYSTORE_FILE" "$KEYSTORE_PASSWORD"
install_ds
