global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'hello-service-job'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['hello-service-1.hello.com:8443']
    tls_config:
      insecure_skip_verify: true
