' ******************************************************************************
' UML sequence diagram that describes the startup flow of the Remal's Docker
' container stack.
'
' Color alias names:
'    https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'
' Since : July, 2023
' Author: Arnold Somogyi <arnold.somogyi@gmail.com>
'
' Copyright (c) 2020-2023 Remal Software and Arnold Somogyi All rights reserved
' ******************************************************************************
@startuml
title
    **Startup flow of the Remal's Docker container stack**
end title

participant Certificate_Authority as pki <<container>>
participant Vault as va <<container>>
participant Directory_Service as ds <<container>>
participant Access_Management as am <<container>>

skinparam sequenceMessageAlign left
skinparam responseMessageBelowArrow false
skinparam maxMessageSize 150
skinparam guillemet true

note over pki: pki.hello.com
/ note over va: vault.hello.com
/ note over ds: ds.hello.com
/ note over am: am.hello.com

note across #Linen: **parallel container initialization: Start SSH servers**
== Certificate Authority container ==
activate pki #HotPink
    pki -> pki: generate CA cert\nca.crt
    pki -> pki: get server cert\npki.hello.com.crt
    pki -> va: container ready signal
== Vault container ==
activate va #Aquamarine
    va -> pki: get server cert
    pki -> va: vault.hello.com.crt
deactivate pki
    va -> va: Vault server\ninstal +config + start
    va -> ds: container ready signal
== Directory Service container ==
deactivate va
activate ds #LimeGreen
    ds -> pki: get server cert
activate pki #HotPink
    pki -> ds: ds.hello.com.crt
deactivate pki
    ds -> ds: LDAP server\ninstal + config + start
    ds -> am: container ready signal
== Access Management container ==
deactivate ds
activate am #DeepSkyBlue
activate pki #HotPink
    am -> pki: get server cert
    pki -> am: am.hello.com.crt
deactivate pki
    am -> am: AM server\ninstal + config + start
    am ->: container ready signal
@enduml