' ******************************************************************************
' UML PlantUML diagram that shows the Remal Docker container hierarchy.
'
' Since : July 2023
' Author: Arnold Somogyi <arnold.somogyi@gmail.com>
'
' Copyright (c) 2020-2024 Remal Software and Arnold Somogyi All rights reserved
' ******************************************************************************
@startuml

<style>
  .STYLE_EXTERNAL {
    RoundCorner 20
    LineThickness 2
    LineColor DarkRed
    BackgroundColor Salmon
  }
  .STYLE_BASE {
    RoundCorner 20
    LineThickness 2
    LineColor Green
    BackgroundColor GreenYellow
  }
  .STYLE_CORE {
    RoundCorner 20
    LineThickness 2
    LineColor Chocolate
    BackgroundColor Gold
  }
  .STYLE_INFRA {
    RoundCorner 20
    LineThickness 2
    LineColor SteelBlue
    BackgroundColor Turquoise
  }
  .STYLE_APP {
    RoundCorner 20
    LineThickness 2
    LineColor Purple
    BackgroundColor HotPink
  }
</style>

title **Docker container hierarchy used by Remal**

sprite $JAR_EXTERNAL jar:archimate/meaning
sprite $JAR_BASE     jar:archimate/goal
sprite $JAR_CORE     jar:archimate/interaction
sprite $JAR_INFRA    jar:archimate/network
sprite $JAR_APP      jar:archimate/physical-equipment

rectangle "alpine"                       as alpine      <<$JAR_EXTERNAL>> <<STYLE_EXTERNAL>>
rectangle "remal-base"                   as base        <<$JAR_BASE>>     <<STYLE_BASE>>
rectangle "OpenJDK-11"                   as java11      <<$JAR_CORE>>     <<STYLE_CORE>>
rectangle "OpenJDK-17"                   as java17      <<$JAR_CORE>>     <<STYLE_CORE>>
rectangle "Private PKI"                  as pki         <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "Apache Tomcat 9"              as tomcat9     <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "ForgeRock Directory Services" as ds          <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "ForgeRock Access Management"  as am          <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "Hashicorp Vault"              as vault       <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "Hashicorp Consul"             as consul      <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "Hashicorp Consul"             as consul      <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "Java-17 Runner"               as javaRunner  <<$JAR_INFRA>>    <<STYLE_INFRA>>
rectangle "User Service"                 as userService <<$JAR_APP>>      <<STYLE_APP>>

alpine     -->  base
base       -->  java11
base       -->  java17
java17     -->  pki
java11     -->  tomcat9
java17     -->  ds
tomcat9    -->  am
base       ---> vault
java17     -->  consul
consul     -->  javaRunner
javaRunner ..   userService

@enduml
