' ******************************************************************************
' UML PlantUML/ArchiMate diagram that shows the Docker container hierarchy used
' by Remal.
'
' Color alias names:
'    https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
'
' Since : Jul, 2023
' Author: Arnold Somogyi <arnold.somogyi@gmail.com>
'
' Copyright (c) 2020-2023 Remal Software and Arnold Somogyi All rights reserved
' ******************************************************************************
@startuml
title
    **Docker container hierarchy used by Remal**
end title

skinparam rectangle<<image>> {
	roundCorner 25
}
sprite $3rdPartyImage jar:archimate/meaning
sprite $remalBaseImage jar:archimate/actor
sprite $remalServiceImage jar:archimate/interface

rectangle "alpine" as alpine <<$3rdPartyImage>><<image>> #Pink
rectangle "remal-base" as base <<$remalBaseImage>><<image>> #PowderBlue
rectangle "OpenJDK-11" as java11 <<$remalBaseImage>><<image>> #PowderBlue
rectangle "OpenJDK-17" as java17 <<$remalBaseImage>><<image>> #PowderBlue
rectangle "Apache Tomcat 9" as tomcat9 <<$remalBaseImage>><<image>> #PowderBlue
rectangle "Private Certificate Authority" as ca <<$remalServiceImage>><<image>> #PaleGreen
rectangle "ForgeRock Directory Services" as ds <<$remalServiceImage>><<image>> #PaleGreen
rectangle "ForgeRock OpenAM" as am <<$remalServiceImage>><<image>> #PaleGreen
rectangle "Hashicorp Vault" as vault <<$remalServiceImage>><<image>> #PaleGreen
rectangle "Hashicorp Consul" as consul <<$remalServiceImage>><<image>> #PaleGreen

alpine *-down-> base
base *-down-> java11
base *-down-> java17
java11 *-down-> tomcat9
java17 *-down-> ca
java17 *-down-> ds
tomcat9 *-down-> am
base *-down-> vault
base *-down-> consul
@enduml
